/**
 * jOOB media gallery — auto-generated by scripts/gen-media-list.mjs
 * Do not edit by hand; run: npm run media:list
 */

export const CAT_PHOTOS = [
  "0402ded7-353d-43b6-9a7e-e35697ca4a4d.jpg",
  "0c2e3348-bba7-4616-be30-b796dcb39797.jpg",
  "0d5c065f-468c-4c3b-b815-fcf6a3db855f.jpg",
  "0e950728-d77a-4f5a-b0c2-769e1318e7e4.jpg",
  "0f4c5b5c-06cf-4d19-a00d-225bfddc785f.jpg",
  "1524451e1730ad600e418552e62ff8d7.jpg",
  "1c0897da-eeaa-4d4f-aefe-c65e72133401.jpg",
  "1d1e2de0-9b18-49be-8bb2-af7a52d84331.jpg",
  "1dc6875d-95dc-41a0-8a65-6de6c4a8fdba.jpg",
  "1e216f50-bc60-4ca8-9fc1-23b387f4ab7c.jpg",
  "2120f9ce-7f10-49ac-8be8-9e1e92ec7af4.jpg",
  "2411643b-33bc-4464-9e66-bcd2ffd42ca7.jpg",
  "24118483-a3df-463e-b83a-073fddc88246.jpg",
  "2616.jpg",
  "281bd776-54b6-4806-befe-c66f4b035255.jpg",
  "296e2c50-2b16-4c60-a5b4-9bede2ccd873.jpg",
  "3177b681-d447-4e41-b795-77cba9dff8b0.jpg",
  "3495.jpg",
  "3496.jpg",
  "3585.jpg",
  "38577dbd-51a2-4ae7-88ac-436811b2c958.jpg",
  "41544b65-17a5-4d75-957f-65c2615fa554.jpg",
  "451fef71-743a-4d42-91d3-d5e0b43ac298.jpg",
  "46256.jpg",
  "47982.jpg",
  "485ac8fb-98a5-4685-8c1b-70f114ab1af4.jpg",
  "4f29c54e-4053-4015-91fd-0053abd1c29a.jpg",
  "55544c89-8887-43b3-80ed-dd0c7a314bcc.jpg",
  "55637f77-f5df-479e-a1b3-0a870d5a9db1.jpg",
  "59798ea5-c093-4c01-b7ab-7fc4ac56b0f5.jpg",
  "5B3C372F-7496-4BC3-BACB-BBC9C6A6E1AD.jpg",
  "5cfbca80-2d5a-4aca-8e41-3a5fa65659c0.jpg",
  "5e0ee585-4007-40c2-8886-fa7dcfe3664a.jpg",
  "6305e51e-7b3f-4315-afa8-3da7e188e569.jpg",
  "63854897-2570-4a94-bd04-7bcad269fbc8.jpg",
  "6842a1d2-300f-4560-97e1-f330ca8b5a72.jpg",
  "6d29a452-b92b-41e7-ac5b-45cd38e0cb87.jpg",
  "7155a98a-a029-4aee-a433-71422273391b.jpg",
  "7310FE68-FB93-45A6-AC16-8B7425250CD2.jpg",
  "75AE176B-1939-41C5-BC59-0824EA1BEF5C.jpg",
  "7681C98B-F881-4E45-A99C-231C3D2ED864.jpg",
  "78f8cc57-611a-453a-a769-93aec6dd8cee.jpg",
  "82bd2815-b376-4f89-b4aa-64f15d92a805.jpg",
  "832d3a99-b2fc-4def-882e-6c9c112a8bd6.jpg",
  "85c3212a-97f3-4891-9c98-e28fba0879cc.jpg",
  "8ef23422-854b-4471-a22b-1a1bb152b44d.jpg",
  "9464867a-cf4c-4902-97a3-b7d84d524789.jpg",
  "9aa56d46-4419-4884-badd-2095f096aeb5.jpg",
  "9b094825-38cf-4846-bb81-ee97e1542757.jpg",
  "9f308f68-0fbf-494c-8444-3fcb7484694b.jpg",
  "a851d01a-f9ec-4fe6-ab6e-d88c84fbe581.jpg",
  "a9ad6ab6-db85-4df7-a1c9-9b53ec40291a.jpg",
  "acf97f87-f09a-4a78-87f3-36ed92662d04.jpg",
  "afd5b999-bfb2-4ad2-91f0-7749ba1afe6b.jpg",
  "B040ACB4-92B5-4FBC-AA55-F8155A115D10.jpg",
  "b113fc78-0687-4682-a32a-765899f8d778.jpg",
  "b6a4a8f9-209e-4411-ba9b-5e6e2ec76a7a.jpg",
  "b92569e2-dfe7-4db7-8404-bf3e4580f1ce.jpg",
  "bbe393e79d7e1ff5948c7f6ed44f6c.jpg",
  "c8ab8e8d-07bd-41de-a475-f9daba8599ff.jpg",
  "ca318363-810f-4fd6-a916-b8f004c6d568.jpg",
  "ccaffbac-7f7c-4307-9891-25d7b461e616.jpg",
  "d25a70b8-2553-44ad-8bbb-287647b13bd1.jpg",
  "d2f85624-07dd-4cc2-b722-0a76fd088462.jpg",
  "db5b6e46-1127-4818-9f69-31e1ba7a78cb.jpg",
  "dd97ab4a-987d-432e-92ab-3b4a82b5d0c6.jpg",
  "df1e9c79-f398-4dea-b506-27fb7d4cf725.jpg",
  "dqs 2025-10-18 164032.657.jpg",
  "dqs 2025-11-10 225518.404.jpg",
  "dqs 2026-01-25 170130.034.jpg",
  "dqs 2026-03-08 1708584EF0E18509BA.jpg",
  "dqs 2026-03-08 1708592769CF8C3C8D.jpg",
  "dqs 2026-03-08 1709012D9BF337B8E3.jpg",
  "e2caebd5-ea90-42e3-a230-bc06741a0a7e.jpg",
  "e809f5b0-184b-443e-8285-31a55530a12c.jpg",
  "f0eeaa6b-6534-40c9-93ae-db8e2c4a1197.jpg",
  "f28e17cfa227b03b0392d9bc5e9984cc.jpg",
  "f2b40940-6946-4b90-acee-771cf3f4980b.jpg",
  "f3764af3-40ff-4db9-b1fe-614c1ac2a708.jpg",
  "f564b7a071567ec34c3963bccdc77f60.jpg",
  "f6452fb5-1e82-4968-917c-c6d702a06a07.jpg",
  "f9baf294-0a8e-499d-8064-98336ed30579.jpg",
  "fb3c011e-427b-480b-8c67-b388872d2ff4.jpg",
  "FC630735-1CDC-425A-8815-750CE85B4D99.jpg",
  "IMG_0719.jpg",
  "IMG_1190.jpg",
  "IMG_1561.jpg",
  "IMG_1565.jpg",
  "IMG_1568.jpg",
  "IMG_1575.jpg",
  "IMG_1576.jpg",
  "IMG_1580.jpg",
  "IMG_1581.jpg",
  "IMG_1582.jpg",
  "IMG_1583.jpg",
  "IMG_1586.jpg",
  "IMG_1587.jpg",
  "IMG_1588.jpg",
  "IMG_1589.jpg",
  "IMG_1593.jpg",
  "IMG_1594.jpg",
  "IMG_1595.jpg",
  "IMG_1596.jpg",
  "IMG_1597.jpg",
  "IMG_1601.jpg",
  "IMG_1663.png",
  "IMG_1664.png",
  "IMG_2121.jpg",
  "IMG_2122.jpg",
  "IMG_2132.jpg",
  "IMG_2133.jpg",
  "IMG_2137.jpg",
  "IMG_2141.jpg",
  "IMG_2142.jpg",
  "IMG_2143.jpg",
  "IMG_2147.jpg",
  "IMG_2148.jpg",
  "IMG_2150.jpg",
  "IMG_2152.jpg",
  "IMG_2156.jpg",
  "IMG_2157.jpg",
  "IMG_2161.jpg",
  "IMG_2164.jpg",
  "IMG_2165.jpg",
  "IMG_2176.jpg",
  "IMG_2177.jpg",
  "IMG_2178.jpg",
  "IMG_2179.jpg",
  "IMG_2180.jpg",
  "IMG_2182.jpg",
  "IMG_2185.jpg",
  "IMG_2186.jpg",
  "IMG_2187.jpg",
  "IMG_2192.jpg",
  "IMG_2193.jpg",
  "IMG_2198.jpg",
  "IMG_2203.jpg",
  "IMG_2204.jpg",
  "IMG_2308.jpg",
  "IMG_2319.jpg",
  "IMG_2334.jpg",
  "IMG_2519.png",
  "IMG_2521.jpg",
  "IMG_2524.jpg",
  "IMG_2636.png",
  "IMG_2781.jpg",
  "IMG_2884.jpg",
  "IMG_3030.jpg",
  "IMG_3033.jpg",
  "IMG_3592.jpg",
  "IMG_8885.jpg",
  "IMG_9186.png",
  "IMG_9457.jpg",
  "IMG_9481.jpg",
  "IMG_9482.jpg",
  "IMG_9516.jpg",
  "IMG_9517.jpg",
  "IMG_9618.jpg",
  "sclassic 2025-10-18 164021.251.jpg",
  "sclassic 2025-10-18 164025.630.jpg",
  "sclassic 2025-10-18 164043.721.jpg",
  "sclassic 2025-10-18 164045.214.jpg",
  "sclassic 2025-10-18 164046.326.jpg",
  "sclassic 2025-10-18 164108.228.jpg",
  "sclassic 2025-10-18 164110.098.jpg",
  "sclassic 2025-10-18 164111.519.jpg",
  "sclassic 2025-10-18 164259.590.jpg"
] as const;

export const CAT_VIDEOS = [
  "018b6215ce13481f8e7c1f38db89f0f6.mp4",
  "08e7a536-22a9-4685-b9c3-5ec90c72fe5a.mp4",
  "162adf3f6125462b846e41dfdcf512bb.mp4",
  "289d3c84a8fe4a1aae861ac6aab23bfa.mp4",
  "325ed0e8f0704a1d9d3df7872ce2556f.mp4",
  "39f20ab5938f435d8ba0e12050f5e960.mp4",
  "3dca015c-1f6b-429d-b868-3cbcc913a333.mp4",
  "4043de48-abad-4db7-ba1e-db2b491c1945.mp4",
  "47108.mp4",
  "49e194b2ee914d14b49b2cec2d456edf.mp4",
  "4e7484f9-4c45-472a-a7d9-8afc9ec1eaf8.mp4",
  "69d969e3-d279-4254-ab1c-5ed1cd800704.mp4",
  "7356da285ca74fa2a598b0a722b1d219.mp4",
  "83ef6e4d5ec643c99d090d21aca5c5bd.mp4",
  "8ae06c4fdd73423395f2bbe6f1d3fa54.mp4",
  "b5090240-8c1f-480b-b488-ef6d1f66df02.mp4",
  "b6d89e0c-f0c3-43e8-899c-5a1a2b8febdc.mp4",
  "b9a5ac44-fac8-4ba9-9389-1803e01718ce.mp4",
  "C5E8C807-629C-4866-92F8-D9E72CB053A0.mp4",
  "cac56a9c-ccba-44b2-ab17-341d24e21f97.mp4",
  "cdbb7132-86f0-44be-94f9-744ca723ae18.mp4",
  "e940d3a8dc574d9ebd7df64cc561ab3f.mp4",
  "edcf5353-e3b9-43e5-9cb8-d8d3f41568be.mp4",
  "ef81c268-b95b-4081-a9fa-7bd66d87d3ed.mp4",
  "front_video.mp4",
  "IMG_0316.mp4",
  "IMG_0317.mp4",
  "IMG_1096.mp4",
  "IMG_1097.mp4",
  "IMG_1196.mp4",
  "IMG_1203.mp4",
  "IMG_1244.mp4",
  "IMG_1557.mp4",
  "IMG_1560.mp4",
  "IMG_1633.mp4",
  "IMG_1671.mp4",
  "IMG_1672.mp4",
  "IMG_1739.mp4",
  "IMG_1741.mp4",
  "IMG_1754.mp4",
  "IMG_1766.mp4",
  "IMG_2120.mp4",
  "IMG_2199.mp4",
  "IMG_2288.mp4",
  "IMG_2289.mp4",
  "IMG_2358.mp4",
  "IMG_2541.mp4",
  "IMG_2883.mp4",
  "IMG_2895.mp4",
  "IMG_3142.mp4",
  "IMG_3143.mp4",
  "IMG_3147.mp4",
  "IMG_3418.mp4",
  "IMG_3421.mp4",
  "IMG_3503.mp4",
  "IMG_3602.mp4",
  "IMG_3747.mp4",
  "IMG_3748.mp4",
  "IMG_4005.mp4",
  "IMG_4154.mp4",
  "IMG_4213.mp4",
  "IMG_4214.mp4",
  "IMG_4215.mp4",
  "IMG_4216.mp4",
  "IMG_4217.mp4",
  "IMG_4501.mp4",
  "IMG_4508.mp4",
  "IMG_4790.mp4",
  "IMG_4871.mp4",
  "IMG_4902.mp4",
  "IMG_5490.mp4",
  "IMG_5524.mp4",
  "IMG_6546.mp4",
  "IMG_6558.mp4",
  "IMG_6562.mp4",
  "IMG_6564.mp4",
  "IMG_6726.mp4",
  "IMG_6748.mp4",
  "IMG_7698.mp4",
  "IMG_7795.mp4",
  "IMG_7797.mp4",
  "IMG_7798.mp4",
  "IMG_7893.mp4",
  "IMG_9460.mp4",
  "IMG_9462.mp4",
  "IMG_9619.mp4",
  "sd1769512796_2.mp4",
  "sd1769512982_2.mp4",
  "sd1769513826_2.mp4"
] as const;

/** Dedicated home-page hero video (from pic/front_video.MP4) */
export const FRONT_VIDEO = "/videos/front_video.mp4";

export function catSrc(file: string): string {
  return `/cats/${file}`;
}

export function videoSrc(file: string): string {
  return `/videos/${file}`;
}

/** Stable pick by seed (job id, index, …) so SSR + client match */
export function pickCat(seed: string | number, offset = 0): string {
  const list = CAT_PHOTOS as readonly string[];
  if (!list.length) return "";
  const s = String(seed);
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  const idx = (h + offset) % list.length;
  return catSrc(list[idx]);
}

export function pickCats(count: number, start = 0): string[] {
  const list = CAT_PHOTOS as readonly string[];
  const out: string[] = [];
  for (let i = 0; i < count && i < list.length; i++) {
    out.push(catSrc(list[(start + i) % list.length]));
  }
  return out;
}

export function pickVideo(seed: string | number, offset = 0): string {
  const list = CAT_VIDEOS as readonly string[];
  if (!list.length) return "";
  const s = String(seed);
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  const idx = (h + offset) % list.length;
  return videoSrc(list[idx]);
}

export function pickVideos(count: number, start = 0): string[] {
  const list = CAT_VIDEOS as readonly string[];
  const out: string[] = [];
  for (let i = 0; i < count && i < list.length; i++) {
    out.push(videoSrc(list[(start + i) % list.length]));
  }
  return out;
}

/** Cat TV playlist URLs (all clips under public/videos) */
export function catTvPlaylist(): string[] {
  return (CAT_VIDEOS as readonly string[]).map(videoSrc);
}

export const JOOB_LOGO = "/brand/joob-logo.png";
export const JOOB_LOGO_SM = "/brand/joob-logo-256.png";
export const JOOB_MASCOT = "/brand/mascot-hero.jpg";
export const JOOB_AVATAR = "/brand/mascot-avatar.png";
export const JOOB_FAVICON = "/brand/favicon-ico.png";
