import type { JobPosting } from "./types";

export const seedJobs: JobPosting[] = [
  {
    id: "j1",
    title: "Café Barista (Summer)",
    titleZh: "咖啡師（暑期）",
    company: "Lotus Lane Café",
    companyZh: "蓮花徑咖啡",
    sector: "fnb",
    lane: "summer",
    district: "Taipa",
    districtZh: "氹仔",
    payMin: 48,
    payMax: 55,
    payUnit: "hourly",
    hoursPerWeek: "20–30 (Jul–Aug)",
    languages: ["Cantonese", "English"],
    description:
      "Prepare drinks, serve guests, keep counter tidy. Ideal for secondary students during summer holidays. Training provided in first week.",
    descriptionZh:
      "調製飲品、招待客人、保持吧台整潔。適合中學生暑期工，首週提供培訓。",
    requirements: ["Age 16+", "Friendly attitude", "Can stand for shifts"],
    requirementsZh: ["年滿16歲", "友善態度", "能長時間站立"],
    skills: ["customer-service", "teamwork", "cantonese"],
    youthFriendly: true,
    minorAllowed: true,
    postedAt: "2026-07-01",
    openings: 3,
    trainingProvided: true,
  },
  {
    id: "j2",
    title: "Retail Sales Associate (Part-time)",
    titleZh: "零售銷售員（兼職）",
    company: "Harbour Fashion Macau",
    companyZh: "海港時裝澳門",
    sector: "retail",
    lane: "part-time",
    district: "Macau Peninsula",
    districtZh: "澳門半島",
    payMin: 50,
    payMax: 58,
    payUnit: "hourly",
    hoursPerWeek: "12–20 evenings & weekends",
    languages: ["Cantonese", "Mandarin"],
    description:
      "Help customers, restock shelves, operate POS. Flexible after-school hours for students aged 16+.",
    descriptionZh: "接待顧客、補貨、操作收銀。適合16歲以上學生的課後彈性工時。",
    requirements: ["Age 16+", "Basic Mandarin", "Weekend availability"],
    requirementsZh: ["年滿16歲", "基本普通話", "週末可上班"],
    skills: ["sales", "customer-service", "mandarin", "pos"],
    youthFriendly: true,
    minorAllowed: true,
    postedAt: "2026-06-28",
    openings: 4,
    trainingProvided: true,
  },
  {
    id: "j3",
    title: "Hotel Front Desk Intern",
    titleZh: "酒店前台實習生",
    company: "Grand Pearl Hotel",
    companyZh: "明珠大酒店",
    sector: "hospitality",
    lane: "internship",
    district: "Cotai",
    districtZh: "路氹",
    payMin: 8000,
    payMax: 10000,
    payUnit: "monthly",
    hoursPerWeek: "40 (full internship week)",
    languages: ["Cantonese", "English", "Mandarin"],
    description:
      "3-month front desk internship: check-in support, guest enquiries, systems shadowing. Path to full-time for strong performers.",
    descriptionZh: "三個月前台實習：協助入住、答覆賓客查詢、系統跟崗。表現優秀可轉全職。",
    requirements: ["Age 18+", "University / IFT student preferred", "English B1+"],
    requirementsZh: ["年滿18歲", "大學生／旅遊學院優先", "英語B1+"],
    skills: ["hospitality", "english", "customer-service", "computers"],
    youthFriendly: true,
    minorAllowed: false,
    postedAt: "2026-06-20",
    openings: 6,
    trainingProvided: true,
  },
  {
    id: "j4",
    title: "Event Assistant (MICE)",
    titleZh: "會展活動助理",
    company: "Delta Events Macau",
    companyZh: "三角洲會展澳門",
    sector: "mice",
    lane: "part-time",
    district: "Cotai",
    districtZh: "路氹",
    payMin: 55,
    payMax: 70,
    payUnit: "hourly",
    hoursPerWeek: "Project-based weekends",
    languages: ["Cantonese", "English"],
    description:
      "Support registration desks, badge control, and guest flow at conferences and exhibitions. Great “1+4” exposure.",
    descriptionZh: "支援會議登記、名牌管理及人流引導。接觸「1+4」會展產業良機。",
    requirements: ["Age 17+", "Can lift light materials", "Weekend events"],
    requirementsZh: ["年滿17歲", "可搬運輕物", "週末活動檔期"],
    skills: ["events", "teamwork", "english", "customer-service"],
    youthFriendly: true,
    minorAllowed: true,
    postedAt: "2026-07-05",
    openings: 10,
    trainingProvided: true,
  },
  {
    id: "j5",
    title: "Clinic Admin Assistant",
    titleZh: "診所行政助理",
    company: "Lotus Wellness Centre",
    companyZh: "蓮花養生中心",
    sector: "big-health",
    lane: "full-time",
    district: "Macau Peninsula",
    districtZh: "澳門半島",
    payMin: 14000,
    payMax: 16000,
    payUnit: "monthly",
    hoursPerWeek: "40",
    languages: ["Cantonese", "Mandarin"],
    description:
      "Reception, appointment booking, and light records for a TCM / wellness clinic under Big Health diversification.",
    descriptionZh: "中醫／養生診所前台、預約及簡易文書，屬大健康多元產業崗位。",
    requirements: ["Age 18+", "Office software", "Polite phone manner"],
    requirementsZh: ["年滿18歲", "辦公軟件", "電話禮貌應對"],
    skills: ["admin", "customer-service", "computers", "mandarin"],
    youthFriendly: true,
    minorAllowed: false,
    postedAt: "2026-06-15",
    openings: 1,
    trainingProvided: true,
  },
  {
    id: "j6",
    title: "Banking Operations Intern",
    titleZh: "銀行營運實習生",
    company: "Pearl River Bank Macau",
    companyZh: "珠江銀行澳門",
    sector: "finance",
    lane: "internship",
    district: "Macau Peninsula",
    districtZh: "澳門半島",
    payMin: 9000,
    payMax: 11000,
    payUnit: "monthly",
    hoursPerWeek: "40",
    languages: ["Cantonese", "English", "Mandarin"],
    description:
      "6-month internship in retail banking ops: KYC support, document checks, customer queue assistance.",
    descriptionZh: "六個月零售銀行營運實習：KYC支援、文件核對、客戶排隊協助。",
    requirements: ["Age 18+", "Business / finance major preferred", "Detail-oriented"],
    requirementsZh: ["年滿18歲", "商科／金融優先", "細心認真"],
    skills: ["finance", "excel", "english", "attention-to-detail"],
    youthFriendly: true,
    minorAllowed: false,
    postedAt: "2026-06-10",
    openings: 2,
    trainingProvided: true,
  },
  {
    id: "j7",
    title: "IT Helpdesk Junior",
    titleZh: "資訊科技支援專員（初級）",
    company: "Cotai Digital Solutions",
    companyZh: "路氹數碼方案",
    sector: "tech",
    lane: "full-time",
    district: "Taipa",
    districtZh: "氹仔",
    payMin: 16000,
    payMax: 19000,
    payUnit: "monthly",
    hoursPerWeek: "40",
    languages: ["Cantonese", "English"],
    description:
      "First-line IT support for SME clients. Hardware setup, password resets, ticket logging. Fresh grads welcome.",
    descriptionZh: "中小企一線IT支援：硬件安裝、密碼重設、工單記錄。歡迎應屆畢業生。",
    requirements: ["Age 18+", "Basic networking knowledge", "Problem-solving"],
    requirementsZh: ["年滿18歲", "基本網絡知識", "解難能力"],
    skills: ["it-support", "troubleshooting", "english", "computers"],
    youthFriendly: true,
    minorAllowed: false,
    postedAt: "2026-07-02",
    openings: 2,
    trainingProvided: true,
  },
  {
    id: "j8",
    title: "Museum Gallery Attendant (Summer)",
    titleZh: "博物館展廳服務員（暑期）",
    company: "Macau Heritage Spaces",
    companyZh: "澳門文化空間",
    sector: "mice",
    lane: "summer",
    district: "Macau Peninsula",
    districtZh: "澳門半島",
    payMin: 46,
    payMax: 52,
    payUnit: "hourly",
    hoursPerWeek: "25–35 summer",
    languages: ["Cantonese", "English", "Portuguese welcome"],
    description:
      "Welcome visitors, protect exhibits, answer simple questions. Quiet environment; great for culture-interested teens 16+.",
    descriptionZh: "接待訪客、保護展品、簡單導覽。環境寧靜，適合熱愛文化的16歲以上青年。",
    requirements: ["Age 16+", "Interest in culture", "Reliable punctuality"],
    requirementsZh: ["年滿16歲", "對文化有興趣", "守時可靠"],
    skills: ["customer-service", "english", "culture"],
    youthFriendly: true,
    minorAllowed: true,
    postedAt: "2026-07-08",
    openings: 5,
    trainingProvided: true,
  },
  {
    id: "j9",
    title: "Kitchen Prep Assistant (Part-time)",
    titleZh: "廚房預備助理（兼職）",
    company: "Street Bowl Kitchen",
    companyZh: "街頭碗食堂",
    sector: "fnb",
    lane: "part-time",
    district: "Macau Peninsula",
    districtZh: "澳門半島",
    payMin: 48,
    payMax: 54,
    payUnit: "hourly",
    hoursPerWeek: "15–25",
    languages: ["Cantonese"],
    description:
      "Vegetable prep, dishwashing support, closing clean-up. Fast-paced F&B; free staff meal per shift.",
    descriptionZh: "蔬果處理、洗碗支援、收工清潔。節奏快的餐飲環境；每更提供員工餐。",
    requirements: ["Age 16+", "Food hygiene mindset", "Can work evenings"],
    requirementsZh: ["年滿16歲", "注重衛生", "可晚更"],
    skills: ["fnb", "teamwork", "hygiene"],
    youthFriendly: true,
    minorAllowed: true,
    postedAt: "2026-07-03",
    openings: 2,
    trainingProvided: false,
  },
  {
    id: "j10",
    title: "Digital Marketing Intern",
    titleZh: "數碼營銷實習生",
    company: "Bay Creative Studio",
    companyZh: "灣區創意工作室",
    sector: "tech",
    lane: "internship",
    district: "Taipa",
    districtZh: "氹仔",
    payMin: 7500,
    payMax: 9000,
    payUnit: "monthly",
    hoursPerWeek: "30–40",
    languages: ["Cantonese", "English", "Mandarin"],
    description:
      "Help with social posts, simple graphics, campaign tracking for local SMEs. Portfolio-friendly projects.",
    descriptionZh: "協助社交媒體內容、簡易設計及活動數據追蹤。利於累積作品集。",
    requirements: ["Age 18+", "Social media fluency", "Basic Canva/Photoshop"],
    requirementsZh: ["年滿18歲", "熟悉社交媒體", "基本Canva／Photoshop"],
    skills: ["digital-marketing", "design", "mandarin", "english"],
    youthFriendly: true,
    minorAllowed: false,
    postedAt: "2026-06-25",
    openings: 2,
    trainingProvided: true,
  },
  {
    id: "j11",
    title: "Wellness Retail Summer Staff",
    titleZh: "養生零售暑期店員",
    company: "Green Leaf Apothecary",
    companyZh: "綠葉養生舖",
    sector: "big-health",
    lane: "summer",
    district: "Taipa",
    districtZh: "氹仔",
    payMin: 49,
    payMax: 56,
    payUnit: "hourly",
    hoursPerWeek: "20–32 Jul–Aug",
    languages: ["Cantonese", "Mandarin"],
    description:
      "Sell wellness products, explain simple product info, maintain displays. Intro to Big Health retail.",
    descriptionZh: "銷售養生產品、講解基本資訊、整理陳列。認識大健康零售的入門崗位。",
    requirements: ["Age 16+", "Interest in health products", "Customer care"],
    requirementsZh: ["年滿16歲", "對健康產品有興趣", "客戶服務意識"],
    skills: ["sales", "customer-service", "mandarin"],
    youthFriendly: true,
    minorAllowed: true,
    postedAt: "2026-07-06",
    openings: 3,
    trainingProvided: true,
  },
  {
    id: "j12",
    title: "After-school Tutor Assistant",
    titleZh: "課後輔導助理",
    company: "Bright Path Learning Centre",
    companyZh: "明途學習中心",
    sector: "education",
    lane: "part-time",
    district: "Macau Peninsula",
    districtZh: "澳門半島",
    payMin: 60,
    payMax: 80,
    payUnit: "hourly",
    hoursPerWeek: "8–15 weekday afternoons",
    languages: ["Cantonese", "English"],
    description:
      "Support tutors with materials, supervise homework time for primary kids. University students preferred.",
    descriptionZh: "協助導師準備教材、看管小學生功課時間。大學生優先。",
    requirements: ["Age 18+", "Patient with children", "Strong academics"],
    requirementsZh: ["年滿18歲", "有耐心", "學業成績良好"],
    skills: ["teaching", "english", "patience", "teamwork"],
    youthFriendly: true,
    minorAllowed: false,
    postedAt: "2026-06-18",
    openings: 4,
    trainingProvided: true,
  },
];
